[package]
name = "dnd-spellbook-maker-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
printpdf = { version = "0.5.0", features = ["embedded_images"] }
rusttype = "0.9.3"
